config/routes.rb
Rails.application.routes.draw do
  root to: "films#index"
  resources :films, only: [:index, :show] do
    collection do
      get :random
    end
  end
  resources :lists do
    resources :bookmarks, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :film
  belongs_to :list

  validates :film, uniqueness: { scope: :list }
end

app/models/film.rb
class Film < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :lists, through: :bookmarks

  include PgSearch::Model
  pg_search_scope :search,
  against: [ :title ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :films, through: :bookmarks

  validates :name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    Rails.logger.info "Bookmark params: #{params.inspect}"
    @bookmark = @list.bookmarks.new(bookmark_params)

    if @bookmark.save
      redirect_to list_path(@list), notice: "Film added to #{@list.name}"
    else
      Rails.logger.error "Bookmark creation failed: #{@bookmark.errors.full_messages.join(', ')}"
      redirect_to list_path(@list), alert: "Failed to add film: #{@bookmark.errors.full_messages.join(', ')}"
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:film_id)
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films =
      if params[:query].present?
        Film.search(params[:query])
      else
        Film.all
      end
  end

  def random
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :index

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks.includes(:film)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      @lists = List.all
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.delete
    redirect_to root_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_icon(icon, classes: nil)
    classes ||= ""
    render "icons/#{icon}", classes: classes
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/films/_card.html.erb
<%= %>
<div class="card-trip">
  <%= image_tag bookmark.photo %>
  <%= link_to films_path(film), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
    <i class="fa-solid fa-trash"></i>
  <% end %>
  <div class="card-trip-infos">
    <div>
      <h2><%= @film.name %></h2>
    </div>
    <h2 class="card-trip-pricing"><%= @film.name %></h2>
  </div>
</div>

app/views/films/index.html.erb
<%= render "shared/navbar" %>
<%= render "shared/banner" %>
<div class="collapse" id="navbarToggleExternalContent" data-bs-theme="light">
  <div class="bg-dark p-4">
    <h5 class="text-body-emphasis h4">Collapsed content</h5>
    <span class="text-body-secondary">Toggleable via the navbar brand.</span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <% current_list_id = params[:id].to_i %>
    <nav class="nav" style="gap: 24px;">
      <% List.all.each do |list| %>
        <% active = list.id == current_list_id %>
        <%= link_to list.name,
                    list_path(list),
                    style: "color: white; #{'text-decoration: underline;' if active}" %>
      <% end%>
    </nav>
    <div class="row justify-content-space-evenly">
      <div class="col-sm-8 my-3">
        <%= form_with url: films_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            style: "width: 150px",
            placeholder: "Enter a movie"
        %>
          <%= submit_tag "Search", name: "", class: "btn btn-outline-secondary mx-2" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>
<div class="container">
  <div class="m-2">
    <%= turbo_frame_tag "films_frame" do %>
      <div class="cards">
        <% @films.shuffle.each do |film| %>
          <% if film.poster %>
            <div class="card">
              <div class="image">
                <%= image_tag url_for(film.poster), alt: "Film poster" %>
              </div>
              <div class="details">
                <div class="center">
                  <h1><%= film.title %><br>
                    <span><%= film.director %> </span></h1>
                  <p> <%= film.year %> </p>
                  <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Add to list
                    </button>
                    <div class="dropdown-menu" style="min-width: 200px;">
                      <% List.all.each do |list| %>
                        <div class="dropdown-item">
                          <%= form_with url: list_bookmarks_path(list), method: :post, data: { turbo_frame: "_top" } do |f| %>
                            <%= hidden_field_tag "bookmark[film_id]", film.id %>
                            <%= f.submit "#{list.name}", class: "btn btn-link text-dark text-start w-100" %>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body style="background-color: rgb(200, 193, 193)">
    <%= yield %>
  </body>
</html>

app/views/lists/_card.html.erb
<div class="card text-center">
  <div class="card-header">
    New List
  </div>
  <div class="card-body">
    <%= render "form", list: @list %>
  </div>
  <div class="card-footer text-muted">
    <p></p>
  </div>
</div>

app/views/lists/_form.html.erb
<%= simple_form_for [@list, Bookmark.new] do |f| %>
  <%= f.input :name %>
  <%= f.submit "Add list", class: "btn-mine" %>
<% end %>

app/views/lists/index.html.erb
<%= render "shared/navbar" %>
<%= render "shared/banner" %>
<div class="container mt-3">
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://static0.colliderimages.com/wordpress/wp-content/uploads/sharedimages/2024/04/onibaba-movie-poster.jpg)">
        <h2><%= link_to list.name, list_path(list), class: "d-flex justify-content-center", style: "color: white;" %></h2>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= render "shared/navbar" %>
<%= render "shared/banner"%>
<div class="mt-5 w-100 d-flex justify-content-center" style="background-color: grey">
  <div class="m-4">
    <%= render "card" %>
  </div>
</div>

app/views/lists/show.html.erb
<%= render "shared/navbar" %>
<%= render "shared/banner" %>
<div class="collapse" id="navbarToggleExternalContent" data-bs-theme="light">
  <div class="bg-dark p-4">
    <h5 class="text-body-emphasis h4">Collapsed content</h5>
    <span class="text-body-secondary">Toggleable via the navbar brand.</span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <% current_list_id = params[:id].to_i %>
    <nav class="nav" style="gap: 24px;">
      <% List.all.each do |list| %>
        <% active = list.id == current_list_id %>
        <%= link_to list.name,
                    list_path(list),
                    style: "color: white; #{'text-decoration: underline;' if active}" %>
      <% end%>
    </nav>
    <div class="row justify-content-space-evenly">
      <div class="col-sm-8 my-3">
        <%= form_with url: films_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            style: "width: 150px",
            placeholder: "Enter a movie"
        %>
          <%= submit_tag "Search", name: "", class: "btn btn-outline-secondary mx-2" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>
<div class="container">
  <div class="cards">
    <% if @bookmarks.any? %>
      <% @bookmarks.each do |bookmark| %>
        <% if bookmark.film.poster %>
          <div class="card">
            <div class="image">
              <%= image_tag url_for(bookmark.film.poster), alt: "Film poster" %>
            </div>
            <div class="details">
              <div class="center">
                <h1><%= bookmark.film.title %><br>
                  <span><%= bookmark.film.director %> </span></h1>
                <p> <%= bookmark.film.year %> </p>
                <p> <%= link_to list_bookmark_path(bookmark.list, bookmark), data: {turbo_method: :delete, turbo_confirm: "Do you wish to remove this film from the list?"} do %>
                    <i class="fa-solid fa-square-minus" style="width: 48px; color: grey"></i>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p><%= "No films have been added to this list yet." %>
        <p>
        <% end %>
      </div>
    </div>

app/views/shared/_banner.html.erb
<div class="banner" style="display: flex; background-image: url('https://preview.redd.it/this-transient-life-1970-v0-jxp1w77hflrd1.jpeg?width=1080&crop=smart&auto=webp&s=3e06db5289527a3452ea27ee54ff2b627f2669be')">
  <div class="container">
    <h1>My Japanese Film Library</h1>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: 'nav-btn' do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-camera-reels" viewBox="0 0 16 16">
        <path d="M6 3a3 3 0 1 1-6 0 3 3 0 0 1 6 0M1 3a2 2 0 1 0 4 0 2 2 0 0 0-4 0"/>
        <path d="M9 6h.5a2 2 0 0 1 1.983 1.738l3.11-1.382A1 1 0 0 1 16 7.269v7.462a1 1 0 0 1-1.406.913l-3.111-1.382A2 2 0 0 1 9.5 16H2a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2zm6 8.73V7.27l-3.5 1.555v4.35zM1 8v6a1 1 0 0 0 1 1h7.5a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1"/>
        <path d="M9 6a3 3 0 1 0 0-6 3 3 0 0 0 0 6M7 3a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
      </svg>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
        <%# else %>
        <!--li class="nav-item"-->
        <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
        <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="collapse" id="navbarToggleExternalContent" data-bs-theme="light">
  <div class="bg-dark p-4">
    <h5 class="text-body-emphasis h4">Collapsed content</h5>
    <span class="text-body-secondary">Toggleable via the navbar brand.</span>
  </div>
</div>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <nav class="nav" style="gap: 24px;">
      <% @lists.each do |list| %>
        <%= link_to list.name, list_path(list), class: "d-flex justify-content-center", style: "color: white;" %>
      <% end%>
    </nav>
    <div class="row justify-content-space-evenly">
      <div class="col-sm-8 my-3">
        <%= form_with url: films_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            style: "width: 150px",
            placeholder: "Enter a movie"
        %>
          <%= submit_tag "Search", name: "", class: "btn btn-outline-secondary mx-2" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>